/*
 * Maman 14 course 20554 question 2 by Yuval Melamed, ID 035870864
 */

import java.util.Objects;

/**
 *
 * @author yuval.melamed
 * @param <T> vertex type
 */
public class Edge<T> {

    private final T fromV;
    private final T toV;

    public Edge(T fromV, T toV) {
        this.fromV = fromV;
        this.toV = toV;
    }

    // hashCode & equals auto-generated by NetBeans
    @Override
    public int hashCode() {
        int hash = 7;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Edge<?> other = (Edge<?>) obj;
        if (!Objects.equals(this.fromV, other.fromV)) {
            return false;
        }
        if (!Objects.equals(this.toV, other.toV)) {
            return false;
        }
        return true;
    }

    public T getFromV() {
        return fromV;
    }

    public T getToV() {
        return toV;
    }
}
