/*
 * Maman 14 course 20554 question 2 by Yuval Melamed, ID 035870864
 */

/**
 * @param <T> vertex type
 * @author yuval.melamed
 */
public class Edge<T> {

    private final T fromV;
    private final T toV;

    public Edge(T fromV, T toV) {
        this.fromV = fromV;
        this.toV = toV;
    }

    // equals & hashCode generated by IntelliJ

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Edge<?> edge = (Edge<?>) o;

        if (getFromV() != null ? !getFromV().equals(edge.getFromV()) : edge.getFromV() != null) return false;
        return getToV() != null ? getToV().equals(edge.getToV()) : edge.getToV() == null;
    }

    @Override
    public int hashCode() {
        int result = getFromV() != null ? getFromV().hashCode() : 0;
        result = 31 * result + (getToV() != null ? getToV().hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return String.format("{%s -> %s}", fromV, toV);
    }

    public T getFromV() {
        return fromV;
    }

    public T getToV() {
        return toV;
    }
}
