/*
 * Maman 14 course 20554 question 2 by Yuval Melamed, ID 035870864
 */

import java.util.Collection;
import java.util.HashSet;

/**
 * @param <T> type of vertex
 * @author yuval.melamed
 */
public class Graph<T> {

    // Hashes will have better internal representation for sets w/o duplicates
    private final HashSet<T> vertexes;
    private final HashSet<Edge<T>> edges;

    public Graph() {
        this.vertexes = new HashSet<>();
        this.edges = new HashSet<>();
    }

    // We were instructed to allow "arrays", so I settle for any collection
    public Graph(Collection<T> vertexes, Collection<Edge<T>> edges) throws
            DuplicateVertexException, DuplicateEdgeException,
            NoSuchVertexException {

        // HashSet's copy-constructor will get rid of duplicates
        this.vertexes = new HashSet<>(vertexes);

        // Detect if we had duplicates & throw exception as instructed
        if (vertexes.size() > this.vertexes.size()) {
            throw new DuplicateVertexException();
        }

        this.edges = new HashSet<>(edges);
        if (edges.size() > this.edges.size()) {
            throw new DuplicateEdgeException();
        }

        // Make sure all edges refer to valid vertexes
        for (Edge<T> edge : edges) {
            if (!isValidEdge(edge)) {
                throw new NoSuchVertexException();
            }
        }
    }

    // Check that both vertexes exists (allows a same-vertex "circular" edge)
    private boolean isValidEdge(Edge<T> edge) {
        return vertexExists(edge.getFromV()) && vertexExists(edge.getToV());
    }

    // Utilize our data-structure's own denial of duplicates to throw exception
    public void addVertex(T vertex) throws DuplicateVertexException {
        if (!getVertexes().add(vertex)) {
            throw new DuplicateVertexException();
        }
    }

    // Again, our data-structure can tell us if a vertex could not be found
    public void removeVertex(T vertex) throws NoSuchVertexException {
        if (!getVertexes().remove(vertex)) {
            throw new NoSuchVertexException();
        }
    }

    // Check both that the vertexes exist & that the edge does not exist yet
    public void addEdge(T fromV, T toV) throws
            NoSuchVertexException, DuplicateEdgeException {
        if (!vertexExists(fromV) || !vertexExists(toV)) {
            throw new NoSuchVertexException();
        }
        if (!getEdges().add(new Edge<>(fromV, toV))) {
            throw new DuplicateEdgeException();
        }
    }

    public void removeEdge(T fromV, T toV) throws NoSuchEdgeException {
        if (!getEdges().remove(new Edge<>(fromV, toV))) {
            throw new NoSuchEdgeException();
        }
    }

    public boolean vertexExists(T vertex) {
        return getVertexes().contains(vertex);
    }

    public boolean edgeExists(Edge<T> edge) {
        return getEdges().contains(edge);
    }

    // Getters
    public HashSet<T> getVertexes() {
        return vertexes;
    }

    public HashSet<Edge<T>> getEdges() {
        return edges;
    }

    // Represent graph as a multi-line report of vertexes & edges
    @Override
    public String toString() {
        return String.format("{%n\tVertexes: %s%n\tEdges: %s%n}", vertexes, edges);
    }

    // Auto-generated by IntelliJ
    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }

        Graph<?> graph = (Graph<?>) o;

        if (getVertexes() != null
                ? !getVertexes().equals(graph.getVertexes())
                : graph.getVertexes() != null) {
            return false;
        }
        return getEdges() != null
                ? getEdges().equals(graph.getEdges())
                : graph.getEdges() == null;
    }

    @Override
    public int hashCode() {
        int vHash = getVertexes() != null ? getVertexes().hashCode() : 0;
        return 31 * vHash + (getEdges() != null ? getEdges().hashCode() : 0);
    }
}
